In [4]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

We will generate dummy data

In [5]:
train_labels = []
train_samples = []

for i in range(50):
    "5% of younger population , these people experienced side effect "
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    "5% of older people who did not have side effect"
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)
    

for i in range(1000):
    "95% of younger population , these people did not experience  side effect "
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)
    
    "95% of older people who experienced side effect"
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)

In [6]:
len(train_labels)

2100

Converting to numpy arrays and shuffling the data to remove any order that was imposed while creating the data

In [7]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels , train_samples = shuffle(train_labels,train_samples)

In [8]:
train_labels,train_samples

(array([0, 1, 0, ..., 0, 1, 1]), array([55, 34, 56, ..., 23, 96, 98]))

In [9]:
# Scaling down training which is in range 13-100 to 0-1 
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [10]:
 train_samples,"--------------------------",scaled_train_samples

(array([55, 34, 56, ..., 23, 96, 98]),
 '--------------------------',
 array([[0.48275862],
        [0.24137931],
        [0.49425287],
        ...,
        [0.11494253],
        [0.95402299],
        [0.97701149]]))

### Quiz questions:

To train any neural network in a supervised learning task, we first need _______________.      
a data set of samples and labels

Samples are also commonly referred to as _______________.    
input data

Labels are also commonly referred to as _______________.     
target data

How will we pass training data to a tf.keras Sequential model?       
Via the Sequential.fit() function


In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Activation
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [12]:
model = Sequential([
    Dense(16, input_shape = (1,), activation = 'relu'),
    Dense(32, activation= 'relu'),
    Dense(2, activation='softmax')
])

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.layers

In [15]:
model.compile(optimizer=Adam(lr= 0.001), loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])

In [16]:
model.fit(scaled_train_samples, train_labels, batch_size=10, epochs=20, shuffle=True, verbose=True, validation_split= 0.1)
# shuffle = True by default , if validation data is added , it will not be shuffled the same data will be used always
# for each batch we should have random data

Epoch 1/20
189/189 [==============================] - 0s 2ms/step - loss: 0.6106 - accuracy: 0.6323 - val_loss: 0.4477 - val_accuracy: 0.8810
Epoch 2/20
189/189 [==============================] - 0s 1ms/step - loss: 0.3718 - accuracy: 0.8974 - val_loss: 0.2434 - val_accuracy: 0.9524
Epoch 3/20
189/189 [==============================] - 0s 1ms/step - loss: 0.2837 - accuracy: 0.9360 - val_loss: 0.1904 - val_accuracy: 0.9571
Epoch 4/20
189/189 [==============================] - 0s 1ms/step - loss: 0.2657 - accuracy: 0.9386 - val_loss: 0.1733 - val_accuracy: 0.9714
Epoch 5/20
189/189 [==============================] - 0s 1ms/step - loss: 0.2579 - accuracy: 0.9392 - val_loss: 0.1639 - val_accuracy: 0.9571
Epoch 6/20
189/189 [==============================] - 0s 1ms/step - loss: 0.2535 - accuracy: 0.9423 - val_loss: 0.1580 - val_accuracy: 0.9714
Epoch 7/20
189/189 [==============================] - 0s 1ms/step - loss: 0.2504 - accuracy: 0.9376 - val_loss: 0.1603 - val_accuracy: 0.9619
Epoch 

Generate test data similar to how train data was generated , in real world we have real data

In [18]:
test_labels = []
test_samples = []

for i in range(10):
    "5% of younger population , these people experienced side effect "
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    "5% of older people who did not have side effect"
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)
    
for i in range(200):
    "95% of younger population , these people did not experience  side effect "
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)
    
    "95% of older people who experienced side effect"
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)

In [19]:
test_labels = np.array(test_labels)

In [22]:
test_samples = np.array(test_samples)

In [24]:
scaled_test_samples = scaler.fit_transform((test_samples).reshape(-1,1))

Predicitng using the previously built model

In [34]:
predictions = model.predict(scaled_test_samples, batch_size=10, verbose=False)

In [35]:
predictions

array([[0.9618372 , 0.03816288],
       [0.19745557, 0.80254436],
       [0.91693425, 0.08306579],
       [0.07680145, 0.9231986 ],
       [0.9597781 , 0.04022191],
       [0.08479214, 0.9152078 ],
       [0.96302575, 0.03697426],
       [0.2401883 , 0.75981164],
       [0.96177   , 0.03822998],
       [0.08479214, 0.9152078 ],
       [0.9628302 , 0.03716986],
       [0.11345463, 0.8865454 ],
       [0.9620377 , 0.03796225],
       [0.014638  , 0.98536193],
       [0.6307786 , 0.3692214 ],
       [0.11345463, 0.8865454 ],
       [0.9636066 , 0.03639338],
       [0.12474363, 0.8752564 ],
       [0.9626991 , 0.03730081],
       [0.15021567, 0.8497844 ],
       [0.9597781 , 0.04022191],
       [0.19745557, 0.80254436],
       [0.9623698 , 0.03763014],
       [0.02481876, 0.97518116],
       [0.49314964, 0.5068503 ],
       [0.3565513 , 0.64344865],
       [0.9597781 , 0.04022191],
       [0.01316344, 0.98683655],
       [0.96223736, 0.03776266],
       [0.3565513 , 0.64344865],
       [0.

In [39]:
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=False)

In [37]:
rounded_predictions

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(rounded_predictions , test_labels)

0.9404761904761905

Confusion matrix to visually see how the model is predicting on new data

## Confusion Matrix