In [4]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

We will generate dummy data

In [5]:
train_labels = []
train_samples = []

for i in range(50):
    "5% of younger population , these people experienced side effect "
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    "5% of older people who did not have side effect"
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)
    

for i in range(1000):
    "95% of younger population , these people did not experience  side effect "
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)
    
    "95% of older people who experienced side effect"
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)

In [6]:
len(train_labels)

2100

Converting to numpy arrays and shuffling the data to remove any order that was imposed while creating the data

In [7]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels , train_samples = shuffle(train_labels,train_samples)

In [8]:
train_labels,train_samples

(array([0, 1, 0, ..., 0, 1, 1]), array([55, 34, 56, ..., 23, 96, 98]))

In [9]:
# Scaling down training which is in range 13-100 to 0-1 
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [10]:
 train_samples,"--------------------------",scaled_train_samples

(array([55, 34, 56, ..., 23, 96, 98]),
 '--------------------------',
 array([[0.48275862],
        [0.24137931],
        [0.49425287],
        ...,
        [0.11494253],
        [0.95402299],
        [0.97701149]]))

### Quiz questions:

To train any neural network in a supervised learning task, we first need _______________.      
a data set of samples and labels

Samples are also commonly referred to as _______________.    
input data

Labels are also commonly referred to as _______________.     
target data

How will we pass training data to a tf.keras Sequential model?       
Via the Sequential.fit() function


In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Activation
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [12]:
model = Sequential([
    Dense(16, input_shape = (1,), activation = 'relu'),
    Dense(32, activation= 'relu'),
    Dense(2, activation='softmax')
])

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.layers

In [15]:
model.compile(optimizer=Adam(lr= 0.001), loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])

In [16]:
model.fit(scaled_train_samples, train_labels, batch_size=10, epochs=20, shuffle=True, verbose=True, validation_split= 0.1)
# shuffle = True by default , if validation data is added , it will not be shuffled the same data will be used always
# for each batch we should have random data

Epoch 1/20
189/189 [==============================] - 0s 2ms/step - loss: 0.6106 - accuracy: 0.6323 - val_loss: 0.4477 - val_accuracy: 0.8810
Epoch 2/20
189/189 [==============================] - 0s 1ms/step - loss: 0.3718 - accuracy: 0.8974 - val_loss: 0.2434 - val_accuracy: 0.9524
Epoch 3/20
189/189 [==============================] - 0s 1ms/step - loss: 0.2837 - accuracy: 0.9360 - val_loss: 0.1904 - val_accuracy: 0.9571
Epoch 4/20
189/189 [==============================] - 0s 1ms/step - loss: 0.2657 - accuracy: 0.9386 - val_loss: 0.1733 - val_accuracy: 0.9714
Epoch 5/20
189/189 [==============================] - 0s 1ms/step - loss: 0.2579 - accuracy: 0.9392 - val_loss: 0.1639 - val_accuracy: 0.9571
Epoch 6/20
189/189 [==============================] - 0s 1ms/step - loss: 0.2535 - accuracy: 0.9423 - val_loss: 0.1580 - val_accuracy: 0.9714
Epoch 7/20
189/189 [==============================] - 0s 1ms/step - loss: 0.2504 - accuracy: 0.9376 - val_loss: 0.1603 - val_accuracy: 0.9619
Epoch 

Generate test data similar to how train data was generated , in real world we have real data

In [18]:
test_labels = []
test_samples = []

for i in range(10):
    "5% of younger population , these people experienced side effect "
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    "5% of older people who did not have side effect"
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)
    
for i in range(200):
    "95% of younger population , these people did not experience  side effect "
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)
    
    "95% of older people who experienced side effect"
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)

In [19]:
test_labels = np.array(test_labels)

In [22]:
test_samples = np.array(test_samples)

In [24]:
scaled_test_samples = scaler.fit_transform((test_samples).reshape(-1,1))

Predicitng using the previously built model

In [34]:
predictions = model.predict(scaled_test_samples, batch_size=10, verbose=False)

In [35]:
predictions

array([[0.9618372 , 0.03816288],
       [0.19745557, 0.80254436],
       [0.91693425, 0.08306579],
       [0.07680145, 0.9231986 ],
       [0.9597781 , 0.04022191],
       [0.08479214, 0.9152078 ],
       [0.96302575, 0.03697426],
       [0.2401883 , 0.75981164],
       [0.96177   , 0.03822998],
       [0.08479214, 0.9152078 ],
       [0.9628302 , 0.03716986],
       [0.11345463, 0.8865454 ],
       [0.9620377 , 0.03796225],
       [0.014638  , 0.98536193],
       [0.6307786 , 0.3692214 ],
       [0.11345463, 0.8865454 ],
       [0.9636066 , 0.03639338],
       [0.12474363, 0.8752564 ],
       [0.9626991 , 0.03730081],
       [0.15021567, 0.8497844 ],
       [0.9597781 , 0.04022191],
       [0.19745557, 0.80254436],
       [0.9623698 , 0.03763014],
       [0.02481876, 0.97518116],
       [0.49314964, 0.5068503 ],
       [0.3565513 , 0.64344865],
       [0.9597781 , 0.04022191],
       [0.01316344, 0.98683655],
       [0.96223736, 0.03776266],
       [0.3565513 , 0.64344865],
       [0.

In [39]:
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=False)

In [37]:
rounded_predictions

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(rounded_predictions , test_labels)

0.9404761904761905

Confusion matrix to visually see how the model is predicting on new data

### Confusion Matrix

In [50]:
from sklearn.metrics import confusion_matrix , plot_confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [58]:
cm = confusion_matrix(test_labels, rounded_predictions)
cm

array([[195,  15],
       [ 10, 200]])

In [61]:
# not working need to fix this
# cm_labels = ['no side effects', 'has side effects']
# plot_confusion_matrix(cm, cm_labels, title= 'CM')

## Save and load the model

In [62]:
model.save('../models/medical_trial.h5')

The save functions saves the :
- Architecture of the model
- The weights the model
- The training config like loss, optimizer
- The state of the optimizer, allowing to resume exactly where we left off

In [63]:
from tensorflow.keras.models import load_model

In [67]:
new_model = load_model("../models/medical_trial.h5") # The same architecture like old model

In [68]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [69]:
new_model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'units': 16,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_1',
    'trainable': True,
    'dtype': 'float32',
    'units': 32,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,


#### If we only want to save the model architecure but not weights and other things

In [72]:
json_string =  model.to_json()

In [73]:
json_string

'{"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "Dense", "config": {"name": "dense", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dens

#### Save only weights

In [74]:
model.save_weights("../models/medical_trial_only_weights.h5")

In [75]:
# loading the weights

model2 = Sequential([
    Dense(16, input_shape = (1,), activation = 'relu'),
    Dense(32, activation= 'relu'),
    Dense(2, activation='softmax')
])


In [76]:
model2.load_weights("../models/medical_trial_only_weights.h5") # passing previously saved model

In [79]:
model2.weights

[<tf.Variable 'dense_3_1/kernel:0' shape=(1, 16) dtype=float32, numpy=
 array([[-0.0881601 ,  0.01425132, -0.5924668 , -0.03857851, -0.01336461,
         -0.4658573 , -0.338716  ,  0.7087602 ,  0.5610516 ,  0.7992864 ,
         -0.04569886, -0.09786454, -0.24511063,  0.24557899, -0.30598316,
          0.5789852 ]], dtype=float32)>,
 <tf.Variable 'dense_3_1/bias:0' shape=(16,) dtype=float32, numpy=
 array([ 0.        , -0.03150105,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.25418225, -0.2268508 , -0.2855868 ,
         0.26869792,  0.        ,  0.        , -0.11582717,  0.        ,
        -0.2843283 ], dtype=float32)>,
 <tf.Variable 'dense_4_1/kernel:0' shape=(16, 32) dtype=float32, numpy=
 array([[ 1.76257640e-01, -3.43990088e-01,  7.78893232e-02,
         -2.07280129e-01,  2.80376971e-02, -1.23713613e-02,
          5.74733019e-02, -2.63981313e-01, -9.16838944e-02,
         -9.94279683e-02,  3.13315302e-01, -2.16032013e-01,
          1.18676335e-01,  1.