### How to get reproducible results

We can get varying results because of the way random weights get initialized and dropouts as well (since droput is random nodes being dropped out)    
To get reproducible results we need to strip the randomness

#### This can be achieved by setting a random seed

In Tensorflow we can set random seed using either Python, Numpy or Tensorflow

In [2]:
import numpy as np
import tensorflow as tf
import random as rn

In [3]:
import os
os.environ['PYTHONHASHSEED'] ='0'

In [5]:
np.random.seed(91) #Setting the seed for numpy generated random numbers

In [6]:
rn.seed(1234) # seed for python

In [8]:
tf.random.set_seed(88)

In TF we should be using single thread if we want reproducible results since multiple thread may not give reproducible results

In [9]:
# Check for TF 2 , not working

# from tensorflow.keras import backend as K
# sess = tf.k

### Intializing baises 

Biases are set per layer , for example for layer with 4 nodes there will be 4 baises each starting with zero
By default Keras initializes biases as 0, not for output layer we did not specify bias , but still it initialized biases as 0

In [3]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
    Dense(4, input_shape=(1,), activation='relu', use_bias=True, bias_initializer='zeros'),
    Dense(2, activation='softmax')
])

In [4]:
model.get_weights()

[array([[0.36837614, 0.13530457, 0.13214874, 0.06553257]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.50807786,  0.16324902],
        [-0.98941636, -0.27336407],
        [ 0.4123869 ,  0.91573286],
        [ 0.12730503, -0.12207603]], dtype=float32),
 array([0., 0.], dtype=float32)]

### Learnable Params or Trainable Params

In [7]:
model.summary() # last column shows learnable params in last column

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 8         
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 10        
Total params: 18
Trainable params: 18
Non-trainable params: 0
_________________________________________________________________
